packages:
  - 'packages/*'
  - 'packages/plugins/*'
  # - 'website'
  - 'examples/*'

catalog:
  '@dayflow/blossom-color-picker': ^2.0.1
  '@preact/preset-vite': ^2.10.3
  '@rollup/plugin-commonjs': ^28.0.2
  '@rollup/plugin-node-resolve': ^16.0.0
  '@rollup/plugin-terser': ^0.4.4
  '@rollup/plugin-typescript': ^12.1.2
  '@tailwindcss/postcss': ^4.2.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/preact': ^3.2.4
  '@testing-library/user-event': ^14.6.1
  '@types/jest': ^29.5.14
  '@types/lodash': ^4.17.13
  '@types/node': ^22.10.2
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  autoprefixer: ^10.4.24
  esbuild: ^0.27.3
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  lucide-react: 0.575.0
  postcss: ^8.5.6
  postcss-import: ^16.1.1
  preact: ^10.28.3
  react: ^18.3.1
  react-dom: ^18.3.1
  rimraf: ^6.1.2
  rollup: ^4.29.1
  rollup-plugin-dts: ^6.3.0
  rollup-plugin-esbuild: ^6.2.1
  rollup-plugin-peer-deps-external: ^2.2.4
  rollup-plugin-postcss: ^4.0.2
  rollup-plugin-svelte: ^7.2.2
  rollup-plugin-visualizer: ^6.0.5
  rollup-plugin-vue: ^6.0.0
  tailwindcss: ^4.2.1
  temporal-polyfill: ^0.3.0
  ts-jest: ^29.4.5
  tslib: ^2.8.1
  typescript: ^5.9.3
  vite: ^5.4.20

catalogMode: prefer
